services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-app
    container_name: docker-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - app-net
    depends_on:
      - mysql
    expose:
      - 9000

  nginx:
    image: nginx:latest
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-net

  mysql:
    image: mysql:8.4
    container_name: app-mysql
    restart: unless-stopped
    env_file:
      - ./src/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_USER: ${DB_USERNAME:-kevin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-net

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: app-smtp4dev
    restart: unless-stopped
    ports:
      - "2525:25"
      - "3000:80"
    networks:
      - app-net

volumes:
  mysql-data:

networks:
  app-net:
    driver: bridge
